Usage: @PROG@ [<options>...]

Options:
  -A, --auto        Auto-detection of program launch mode.
  -C, --continue    Continue previously started testing.
  -F, --finish      Finish previously started testing.
  -S, --start       Start new testing.
  -b, --batch       Do not use input and dialogs for settings.
  -c, --color=<M>   Change console color mode:
                    "auto": auto-detection mode, used by default;
                    "always": always use colors in the console;
                    "never": never use colors in the console.
  -d, --date=<F>    Date in YYYY-MM-DD format, defining part
                    of the name of the archive with the results,
                    and the public archive of the p9/p10/Sisyphus
                    repository.
  -n, --name=<N>    Computer name used as part of archive name.
      --no-autorun  Disable autorun via desktop file.
      --no-sources  Disable APT sources changes.
      --no-update   Disable APT sources changes, disable
                    full system and Linux kernel updates.
      --update      Enable APT sources changes, enable
                    full system and Linux kernel updates
                    (this is default behavior).
      --uid=<ID>    For internal use only.
      --desktop-icon
  -v, --version     Show the version of this program.
  -h, --help        Show this help message.

